### ISSUE TITLE
How to remove Brunch?

### ISSUE THREAD

**Issue by Naazim-Apps** [sebanc/brunch#1939] opened 2023-10-09 02:53 UTC
Hi, I loved the Brunch project but I want to go back to Windows. I would like to remove Brunch but can't get to BIOS. I can however access the GRUB command line. Can I get help here? @sebanc I saw you helped someone else but it's not working. Pictures below.
![IMG_20231008_195313.jpg](https://github.com/sebanc/brunch/assets/111462062/dec59224-c695-400f-9d81-0c430db87332)

![IMG_20231008_195302.jpg](https://github.com/sebanc/brunch/assets/111462062/41cdf835-e8c1-42c1-b387-b7b9736cb95d)

![IMG_20231008_195801.jpg](https://github.com/sebanc/brunch/assets/111462062/4cd29091-1a20-4a50-be62-49fd72bc86dd)

**Comment by ZProLegend007** [comment] 2023-10-09 03:18
How did you install brunch? What device are you using and what OSs are installed, then we can go from there :) Did you set it up so that you can only boot brunch?

**Comment by Naazim-Apps** [comment] 2023-10-10 02:05
> How did you install brunch? What device are you using and what OSs are installed, then we can go from there :) Did you set it up so that you can only boot brunch?

If you Google "Brunch beebom tutorial" and click the Beebom link from 2022, those are the steps I followed.

I am using a HP laptop with 4GB RAM, and an Intel Celeron N4020 processor.
Windows 11 was installed before, but I completely replaced it with Brunch.

And yeah, I set it up so I can only boot brunch.

**Comment by ZProLegend007** [comment] 2023-10-12 05:12
You need to make a windows installer USB and then boot into that to install Windows 11 again. Also you may need to access BIOS to do that so look around online for the specific keys that need to be pressed on your device to access that.

**Comment by Naazim-Apps** [comment] 2023-10-12 13:52
> You need to make a Windows installer USB and then boot into that to install Windows 11 again. Also you may need to access your BIOS to do that so look around online for the device specific keys that need to be pressed during boot to access that. (It's usually a function key so try mashing them a few times while booting.)

Yes, I have tried to get into BIOS. I know the key, I've used it before, but it's like the Brunch boot screen is as far as I can get to BIOS.

**Comment by Naazim-Apps** [comment] 2023-11-01 23:32
Hey, just wanted to let you know that I finally got to BIOS, thanks for trying to help.

**Comment by ZProLegend007** [comment] 2023-11-02 02:00
Good to hear! Make sure to close the issue if the problem is solved :)

**Closed** 2023-11-04 21:58 UTC
