### ISSUE TITLE
Wifi doesnt work after sleep

### ISSUE THREAD

**Issue by hehecoi222** [sebanc/brunch#1013] opened 2021-04-17 14:22 UTC
After updated to r89 image and brunch, my Surface Pro 3 cant connect to the internet after sleep. When running Connectivity Diagnostics it showed that Captive Portal was in "warning" status. I could connect to every wifi spots but all of them couldnt connect to the internet, while ethernet is still working good.
Shutdown could solve this problem but it is not convenient to do that all the time

**Comment by asukumar10248** [comment] 2021-04-24 11:46
it is embeded in chrome os to turn of wifi in sleep mode

**Comment by ecaron** [comment] 2021-04-24 15:52
@hehecoi222, would you feel comfortable closing this as a duplicate of #953? (Which itself is a duplicate of #42, and the recent work on https://github.com/linux-surface/kernel/issues/20 might squash this once and for all...)

**Comment by hehecoi222** [comment] 2021-04-25 10:02
ive followed the solution of # 42 but the problem was not fixed

**Comment by ecaron** [comment] 2021-04-25 18:44
@hehecoi222 I understand that 42 didn't fix it. My recommendation was closing this as a duplicate of 953, so more eyes are on that ticket (which is where I'm writing my progress reports).

**Closed** 2021-04-27 14:36 UTC
