### ISSUE TITLE
ChromeOS launches UI before all pre-signin components required for Android are loaded

### ISSUE THREAD

**Issue by khanhtranngoccva** [sebanc/brunch#227] opened 2020-05-30 05:04 UTC
Normally, in Chromebooks, these components takes nearly no time to load at all, so one can log in right after the UI appears and experience no problems with the Android container. But custom computers running Chrome take up to 1 minute to fully load them. The last component integral for Android to be loaded before first sign-in is "capability", and 30 secs after the UI appears, it spawns a log line stating that it is loaded and "using 32-bit capabilities". #164

**Comment by Skawtnyc** [comment] 2020-05-30 22:52
Yes, this is normal behavior for Chrome OS. It makes sense since Android configuration is tied to the account logging in.

**Comment by khanhtranngoccva** [comment] 2020-05-31 23:30
![83122060-4c919200-a0fd-11ea-953e-a0dfef01c047](https://user-images.githubusercontent.com/61155608/83365256-0c6a3200-a3d1-11ea-90fd-f31f8737b0af.png)
It takes an abnormal amount of 30-80 seconds since the blue step started for the red step to finish. If I try to sign in earlier, Android container won't work. The problem here is how to make the red step finish before the blue one starts.

**Comment by Skawtnyc** [comment] 2020-06-01 00:50
I've been working on a project to automatically set the DPI upon bootup to fix the Android scaling that the devs broke and refused to fix. Turns out that by default any DPI changes would be saved past reboot, but they inserted a line into an init file that resets the DPI to 240 (regardless of device resolution). This init file (and others) only trigger AFTER you've logged in.

The problem for me was that I was having the damnedest time trying to figure out when my init script ran. We only have access to the ChromeOS init scripts in dev mode after enabling read/write. And they all execute before the init scripts in the Android container. There is no way around this, either. The solution was to add a sleep command at the beginning of my script, which basically made it wait long enough for the Android init scripts to finish before executing. My Surface Go needs 10 seconds. My Lenovo Duet needs 20.

**Comment by khanhtranngoccva** [comment] 2020-06-01 04:11
Then how can I do it please? I've figured out the cause, but I haven't worked out any solutions.

**Comment by Skawtnyc** [comment] 2020-06-01 14:39
What are you trying to accomplish? My script is specifically for addressing Android scaling.

**Comment by sebanc** [comment] 2020-06-26 11:27
Duplicate of #164

**Closed by sebanc** 2020-06-26 11:27 UTC
