### ISSUE TITLE
stuck at ChromeOS logo, black screen

### ISSUE THREAD

**Issue by YazWare** [sebanc/brunch#1959] opened 2023-11-02 16:39 UTC
I have an HP Stream 14-ax016nf
- Intel Celeron N3060 (Braswell)
- Intel HD Graphics 400
I used the octopus recovery r118, brunch r118.
Everything boots properly until I get into the ChromeOS logo, it gets stuck for hours. I'm booting from an USB.
It's my first time with Brunch and ChromeOS so maybe that's something obvious but I don't really know a lot about these.

**Comment by XenHat** [comment] 2023-11-03 03:13
Duplicate of many, many issues here.

Try booting ChromeOS 114 on a cpu this old. my two machines with Haswell processors refuse to boot or update to anything newer.

**Comment by YazWare** [comment] 2023-11-03 16:20
thank you, working fine now

**Closed** 2023-11-03 16:20 UTC

**Comment by Haxker-00** [comment] 2024-09-05 05:27
for intel i7 2nd gen??

**Comment by Haxker-00** [comment] 2024-09-05 05:27
> Duplicate of many, many issues here.
> 
> Try booting ChromeOS 114 on a cpu this old. my two machines with Haswell processors refuse to boot or update to anything newer.

for 97 2nd gen??
