### ISSUE TITLE
Play store and android apps are not opening

### ISSUE THREAD

**Issue by Sarojpadhy** [sebanc/brunch#74] opened 2020-04-27 13:01 UTC
The playstore and other android apps installed are not opening . 

using chrome os Rammus recovery 80 and Brunch r81 k4.19 testing 20200419

PC
Intel pentium G3240
Intel integrated GPU

![Screenshot 2020-04-27 at 6 12 20 PM](https://user-images.githubusercontent.com/64416779/80375078-4f5a5680-88b5-11ea-8419-72be8671ba20.png)

**Comment by NSbuilder** [comment] 2020-04-27 13:29
Same for me, except I used eve image instead of rammus so it might be this

**Comment by lfom** [comment] 2020-04-27 13:46
Can you open `chrome://flags`? Your processor does not have support for AES nor Trusted Exection, maybe it cannot enable the security layer properly... What is the result of the command below?
`cat /var/log/messages | grep -i "android|arc"`

**Comment by Sarojpadhy** [comment] 2020-04-27 13:53
> Can you open `chrome://flags`? Your processor does not have support for AES nor Trusted Exection, maybe it cannot enable the security layer properly... What is the result of the command below?
> `cat /var/log/messages | grep -i "android|arc"`

Yes  i can open `chrome://flags`

I didn't got that [> `cat /var/log/messages | grep -i "android|arc"`] . 
Can you explain it in a simple way

**Comment by lfom** [comment] 2020-04-27 13:56
You must open the shell: CTRL + ALT +T to open crosh, then type `shell`, then copy and paste the command, and paste back the results here...

**Comment by Sarojpadhy** [comment] 2020-04-27 13:58
> You must open the shell: CTRL + ALT +T to open crosh, then type `shell`, then copy and paste the command, and paste back the results here...

bash: cat/var/log/messages: No such file or directory

**Comment by lfom** [comment] 2020-04-27 14:04
You didn't type it correctly (there is a missing space after cat), it is better to copy and paste, that works differently in crosh.

**Comment by Sarojpadhy** [comment] 2020-04-27 14:07
> You didn't type it correctly (there is a missing space after cat), it is better to copy and paste, that works differently in crosh.

nothing happens if i insert a space 

chronos@localhost / $ cat /var/log/messages | grep -i "android|arc"
chronos@localhost / $

**Comment by lfom** [comment] 2020-04-27 14:52
My bad, `grep` in chrosh shell is very limited, the command below should be enough to show any issues:
`cat /var/log/messages | grep Android`

**Comment by Sarojpadhy** [comment] 2020-04-27 14:59
> My bad, `grep` in chrosh shell is very limited, the command below should be enough to show any issues:
> `cat /var/log/messages | grep Android`

chronos@localhost / $ cat /var/log/messages | grep Android
2020-04-27T15:34:59.256519+05:30 INFO session_manager[1127]: [INFO:session_manager_impl.cc(1779)] Android container with PID 2095 stopped
2020-04-27T15:35:00.002168+05:30 ERR session_manager[1127]: [ERROR:session_manager_impl.cc(1318)] Error getting Android container pid.
2020-04-27T15:35:00.002322+05:30 ERR session_manager[1127]: [ERROR:dbus_util.cc(13)] CreateError(...): Domain=dbus, Code=org.chromium.SessionManagerInterface.ContainerShutdownFail, Message=Error getting Android container pid.
2020-04-27T18:03:29.662719+05:30 INFO session_manager[1126]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 1995
2020-04-27T18:03:29.972645+05:30 INFO session_manager[1126]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 1995
2020-04-27T18:03:58.453733+05:30 INFO session_manager[1126]: [INFO:session_manager_impl.cc(1779)] Android container with PID 1995 stopped
2020-04-27T18:18:35.099827+05:30 INFO session_manager[1125]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 1860
2020-04-27T18:18:42.718623+05:30 INFO session_manager[1125]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 1860
2020-04-27T18:19:12.093890+05:30 INFO session_manager[1125]: [INFO:session_manager_impl.cc(1779)] Android container with PID 1860 stopped
2020-04-27T20:25:58.871298+05:30 INFO session_manager[1287]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 2002
2020-04-27T20:26:07.413353+05:30 INFO session_manager[1287]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 2002

**Comment by lfom** [comment] 2020-04-27 15:16
Weird, it looks fine... Are you running brunch from a USB flash drive? Does it have enough free space? What is the result of the command below?
`lsblk | grep container`

**Comment by Sarojpadhy** [comment] 2020-04-27 15:20
> Weird, it looks fine... Are you running brunch from a USB flash drive? Does it have enough free space? What is the result of the command below?
> `lsblk | grep container`

- No i installed it from the USB with Linux, as shown in the following video [https://www.youtube.com/watch?v=4gZYV0RWJQ8](url)
- Result 
loop1           7:1    0 486.8M  1 loop /opt/google/containers/android/rootfs/root
loop2           7:2    0     4K  1 loop /opt/google/containers/arc-sdcard/mountpoints/container-root
loop3           7:3    0     4K  1 loop /opt/google/containers/arc-obb-mounter/mountpoints/container-root

**Comment by Sarojpadhy** [comment] 2020-04-27 15:21
Well a good news, i tried running the play store again now, and it successfully opened.

**Comment by lfom** [comment] 2020-04-27 15:27
Good, everything looked normal. Maybe you just needed to wait for it to finish downloading and installing. Please close the issue.

**Comment by Sarojpadhy** [comment] 2020-04-27 15:29
> Good, everything looked normal. Maybe you just needed to wait for it to finish downloading and installing. Please close the issue.

I shut down the pc at that time, and when i booted now it took some time to boot and did some stuff like loading rootfc etc.
Now its working fine.
Hope i won't get that issue again.
thank you for your time and effort.

**Comment by Sarojpadhy** [comment] 2020-04-28 06:54
@lfom facing the same problem again. 
chronos@localhost / $ cat /var/log/messages | grep Android
2020-04-27T15:34:59.256519+05:30 INFO session_manager[1127]: [INFO:session_manager_impl.cc(1779)] Android container with PID 2095 stopped
2020-04-27T15:35:00.002168+05:30 ERR session_manager[1127]: [ERROR:session_manager_impl.cc(1318)] Error getting Android container pid.
2020-04-27T15:35:00.002322+05:30 ERR session_manager[1127]: [ERROR:dbus_util.cc(13)] CreateError(...): Domain=dbus, Code=org.chromium.SessionManagerInterface.ContainerShutdownFail, Message=Error getting Android container pid.
2020-04-27T18:03:29.662719+05:30 INFO session_manager[1126]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 1995
2020-04-27T18:03:29.972645+05:30 INFO session_manager[1126]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 1995
2020-04-27T18:03:58.453733+05:30 INFO session_manager[1126]: [INFO:session_manager_impl.cc(1779)] Android container with PID 1995 stopped
2020-04-27T18:18:35.099827+05:30 INFO session_manager[1125]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 1860
2020-04-27T18:18:42.718623+05:30 INFO session_manager[1125]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 1860
2020-04-27T18:19:12.093890+05:30 INFO session_manager[1125]: [INFO:session_manager_impl.cc(1779)] Android container with PID 1860 stopped
2020-04-27T20:25:58.871298+05:30 INFO session_manager[1287]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 2002
2020-04-27T20:26:07.413353+05:30 INFO session_manager[1287]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 2002
2020-04-27T22:34:21.995810+05:30 INFO session_manager[1287]: [INFO:session_manager_impl.cc(1779)] Android container with PID 2002 stopped
2020-04-27T22:34:22.660073+05:30 ERR session_manager[1287]: [ERROR:session_manager_impl.cc(1318)] Error getting Android container pid.
2020-04-27T22:34:22.660267+05:30 ERR session_manager[1287]: [ERROR:dbus_util.cc(13)] CreateError(...): Domain=dbus, Code=org.chromium.SessionManagerInterface.ContainerShutdownFail, Message=Error getting Android container pid.
2020-04-28T12:18:44.569688+05:30 INFO session_manager[1160]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 1847
2020-04-28T12:18:52.549282+05:30 INFO session_manager[1160]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 1847
2020-04-28T12:19:20.683237+05:30 INFO session_manager[1160]: [INFO:session_manager_impl.cc(1779)] Android container with PID 1847 stopped

**Comment by sebanc** [comment] 2020-04-28 06:56
Hi, Could you try deleting google sync ?
https://support.google.com/chromebook/answer/2914794?hl=en

**Comment by Sarojpadhy** [comment] 2020-04-28 07:00
> Hi, Could you try deleting google sync ?
> https://support.google.com/chromebook/answer/2914794?hl=en

![canvas](https://user-images.githubusercontent.com/64416779/80456919-09040680-894c-11ea-9e9a-6d266f9387ab.png)

**Comment by sebanc** [comment] 2020-04-28 09:28
Have you rebooted after deleting sync ? It's still not working ?

**Comment by Sarojpadhy** [comment] 2020-04-28 12:20
> Have you rebooted after deleting sync ? It's still not working ?

Yes i rebooted twice, but it didn't worked, now i signed out and sign in again. and it's working.
Don't know what's wrong.

**Comment by sebanc** [comment] 2020-04-28 12:31
Are you booting chromeos on a usb flashdrive ?

**Comment by Sarojpadhy** [comment] 2020-04-28 12:34
> Are you booting chromeos on a usb flashdrive ?

No, i have installed it on my hard disk.

**Comment by sebanc** [comment] 2020-04-28 12:35
Ok, I am currently refactoring the kernel and hope it will work better with the next release.

**Comment by Sarojpadhy** [comment] 2020-04-28 12:44
> Ok, I am currently refactoring the kernel and hope it will work better with the next release.

Thank you
BTW it always shows some processes for a minute while booting, is it normal  ?

**Comment by sebanc** [comment] 2020-04-28 13:32
If you mean the text on screen before the bootanimation appears, it's normal. It's so that I can debug issues, you can add "console=" to the kernel command line (after cros_debug) if you want a text free boot.

**Comment by Nootboot64** [comment] 2020-04-28 17:52
Hi, sorry, I have a similar problem. After booting for the second time (after I set it up, and am done with my computer for the day) Android apps do not work. No matter what, I can't figure it out. I've tried Croissant and Brunch images, with eve for Croissant and rammus for Brunch. These are my
 command results.
```
chronos@localhost / $ cat /var/log/messages | grep Android
2020-04-28T08:52:03.339357+00:00 INFO session_manager[1063]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 2348
2020-04-28T12:53:10.257379+00:00 INFO session_manager[1063]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 2348
2020-04-28T17:29:37.618466+00:00 INFO session_manager[1063]: [INFO:session_manager_impl.cc(1779)] Android container with PID 2348 stopped
2020-04-28T17:29:38.226238+00:00 ERR session_manager[1063]: [ERROR:session_manager_impl.cc(1318)] Error getting Android container pid.
2020-04-28T17:29:38.226919+00:00 ERR session_manager[1063]: [ERROR:dbus_util.cc(13)] CreateError(...): Domain=dbus, Code=org.chromium.SessionManagerInterface.ContainerShutdownFail, Message=Error getting Android container pid.
2020-04-28T13:31:28.471383-04:00 INFO session_manager[1060]: [INFO:session_manager_impl.cc(1695)] Started Android container with PID 2504
2020-04-28T13:31:29.088068-04:00 INFO session_manager[1060]: [INFO:session_manager_impl.cc(1260)] Android container is running with PID 2504
2020-04-28T13:32:00.121828-04:00 INFO session_manager[1060]: [INFO:session_manager_impl.cc(1779)] Android container with PID 2504 stopped
```
If you have any suggestions or help you can give me it would be nice. Thank you for your work on this project.

**Comment by sebanc** [comment] 2020-04-28 17:55
@Nootboot64 If you have not already done it, you try deleting google sync ?
https://support.google.com/chromebook/answer/2914794?hl=en

**Comment by Nootboot64** [comment] 2020-04-28 17:56
I did but am I supposed to log back in afterwards?

**Comment by sebanc** [comment] 2020-04-28 17:57
Yes, try to reboot afterwards

**Comment by Nootboot64** [comment] 2020-04-28 17:59
Ok, thank you

**Comment by Nootboot64** [comment] 2020-04-28 18:03
It didn't work... I think I did it right

**Comment by sebanc** [comment] 2020-04-28 18:09
@Nootboot64 Are you on brunch currently or on croissant ? the issues with android are not the same on both

**Comment by Nootboot64** [comment] 2020-04-28 18:09
Brunch

**Comment by sebanc** [comment] 2020-04-28 18:13
@Nootboot64 Ok, what's your laptop model ?

**Comment by Nootboot64** [comment] 2020-04-28 18:14
I have a Lenovo Ideapad 110 with 6gb ram, an Intel core i3, and integrated intel graphics.

**Comment by Sarojpadhy** [comment] 2020-04-29 12:11
I have to reset sync every time i face this issue .

**Comment by Nootboot64** [comment] 2020-04-29 13:19
After seeing your latest commit, I looked up which cpu generation I have, and came up with Intel Core i3-6100U CPU, which is a 6th gen cpu. So I still don't know why I'm having play store problems, but at least I know that it most likely isn't being caused by the recovery image (I'm using rammus).

**Comment by juicypop** [comment] 2020-04-30 16:28
> If you mean the text on screen before the bootanimation appears, it's normal. It's so that I can debug issues, you can add "console=" to the kernel command line (after cros_debug) if you want a text free boot.

There's a boot animation? I just tried your "console=" but this just shows an empty console with cursor until the login screen appears. 
Is there any way to have a custom boot animation with Chrome os?

**Comment by sebanc** [comment] 2020-05-03 06:29
Hi, I have reviewed the kernel config a lot in the new testing release, could you try it ?

**Comment by Nootboot64** [comment] 2020-05-03 12:51
Yes, luckily there's a way to dual boot cause I'm using windows now.

**Comment by Nootboot64** [comment] 2020-05-03 16:06
Sorry for doing a complete 180 on this, but I just cannot figure out how to dual boot, and I don't want to spend 4 hours on this. Sorry.

**Comment by Nootboot64** [comment] 2020-05-04 16:52
Ok, I actually decided to install it, do you have any specific things I should test?
Also, is there a way to check what version of brunch I have?

**Comment by sebanc** [comment] 2020-05-04 17:05
@Nootboot64 There is currently no way to know which brunch version you currently have but that's something I will try to implement. If you have a doubt, update to the latest version by running `sudo chromeos-update -f <path to the latest brunch archive>`.

Try to see with the new version if you have regressions compared to your current build but for now it appears to be quite stable.

**Comment by Nootboot64** [comment] 2020-05-04 17:19
Sorry, but I rebooted and the android apps don't boot again. I hope I can help test with the next release

**Comment by sebanc** [comment] 2020-05-09 18:05
@Nootboot64 @Sarojpadhy Could you try booting with "add_efi_memmap" on the kernel command line (after cros_debug) ?

**Comment by MiLKQC** [comment] 2020-05-09 20:15
> @Nootboot64 @Sarojpadhy Could you try booting with "add_efi_memmap" on the kernel command line (after cros_debug) ?

Hi, I have the same problem, I added the command but it didn't work after rebooting.

**Comment by sebanc** [comment] 2020-05-13 12:05
Hi, regarding this issue, the fact that google play works on first boot and then stops working most likely means that there is an issue with your profile / Google account setup.

Could you try the "Clear cache & data from Google Play Services" mentioned here?
https://support.google.com/googleplay/answer/7512202?hl=en

**Comment by nicogig** [comment] 2020-05-17 16:03
Hello, I'm having the same issue as @Nootboot64. The log output I gathered is the same as his when using cat and grep. Using the "add_efi_memmap" did not fix it, as well as resetting the sync options.

As a last attempt, I tried deleting the Play Store and reinstalling it from Chrome OS's settings, but now it does not install anymore ("Something went wrong" error shows up).

If it helps, the target device is a Lenovo Thinkpad Helix 2 (Intel Core M-5Y71) with 8GB RAM and 256GB SSD. The image used is rummus. It is currently booting with the options "enable_updates" (updated to r81, the problem was in r80 as well), "suspend_s3", and "advanced_als".

**Comment by sebanc** [comment] 2020-05-17 16:23
General question: Have you setup chromeos on several devices or just one ? Just to see if it could be related to that

**Comment by nicogig** [comment] 2020-05-17 16:44
> General question: Have you setup chromeos on several devices or just one ? Just to see if it could be related to that

Just one, the one specified above.

After removing Play Services, I tried rebooting a couple of times and Play Store seems to be up and running again. Will let you know if the issue comes up again.

**Comment by harun911** [comment] 2020-05-17 18:41
I encountered the same problem today on my laptop. I googled around a bit and found out that even official chromebooks sometimes have this problem. What works is, to let the OS sit and wait at the login screen for 2 minutes and then login. I think it probably has to do with the android emulator/environment not being fully booted up yet when logging in to fast.

**Comment by nicogig** [comment] 2020-05-19 16:47
> I encountered the same problem today on my laptop. I googled around a bit and found out that even official chromebooks sometimes have this problem. What works is, to let the OS sit and wait at the login screen for 2 minutes and then login. I think it probably has to do with the android emulator/environment not being fully booted up yet when logging in to fast.

This seems to be it! I've been messing with my setup for the past day and just leaving it rest for a few minutes at the login screen fixed my issues.

**Comment by khanhtranngoccva** [comment] 2020-05-21 09:11
Well I don't know why the container keeps suffering from sigterm.
INFO arc-container[2462]: [INFO:run_oci.cc(871)] Sending signal 15 to container android-run_oci

**Comment by sebanc** [comment] 2020-05-22 09:41
Hi, thanks for the investigations you have done of this, the 2 minutes delay before bootup technique is interesting and I tried something to fix it in this release:
https://github.com/sebanc/brunch-testing/releases

Could you give it a try and see if you still need the 2 minutes delay to have android apps working ?

**Comment by nicogig** [comment] 2020-05-22 11:15
> Hi, thanks for the investigations you have done of this, the 2 minutes delay before login workaround is interesting and I tried something to fix it in this release:
> https://github.com/sebanc/brunch-testing/releases
> 
> Could you give it a try and see if you still need the 2 minutes delay to have android apps working ?

Tried it and looked in straight after boot, without waiting the 2 minutes. Play Store launched right away!

**Comment by harun911** [comment] 2020-05-22 13:46
I don't have this laptop at my disposal anymore, so I can't test your fix sebanc. I'll try to install the whole thing on a different laptop later (i5 6200u, nvidia mx150). What I remember from my findings with the other laptop, was that after the rebuilding of the root file, it always worked instantly. The problem started appearing every consecutive (re)boot after. Maybe you can try to validate that too @nicogig?

**Comment by nicogig** [comment] 2020-05-22 13:57
> I don't have this laptop at my disposal anymore, so I can't test your fix sebanc. I'll try to install the whole thing on a different laptop later (i5 6200u, nvidia mx150). What I remember from my findings with the other laptop, was that after the rebuilding of the root file, it always worked instantly. The problem started appearing every consecutive (re)boot after. Maybe you can try to validate that too @nicogig?

I did a couple of reboots to be on the safe side, and Android Apps are working as expected without performing the workaround.

**Comment by khanhtranngoccva** [comment] 2020-05-28 09:11
The order of execution of fscrypt and cgroup might be why waiting for 2 minutes work. Can you check these screenshots?
![Screenshot 2020-05-28 at 4 07 46 PM](https://user-images.githubusercontent.com/61155608/83122465-e22d2180-a0fd-11ea-91c7-3b4f97b934bd.png)
![Screenshot 2020-05-28 at 4 07 12 PM](https://user-images.githubusercontent.com/61155608/83122470-e3f6e500-a0fd-11ea-9389-8093c2d00587.png)

**Closed** 2020-06-26 11:04 UTC

**Comment by karthikdhanavath** [comment] 2020-10-15 09:37
please help me playstore not opening
![Uploading Screenshot 2020-10-15 at 3.07.31 PM.png…]()

**Comment by goxtozo** [comment] 2021-07-15 14:11
> My bad, `grep` in chrosh shell is very limited, the command below should be enough to show any issues:
> `cat /var/log/messages | grep Android`

![IMG_20210715_193944](https://user-images.githubusercontent.com/82498022/125802257-48e2719e-2dde-4886-90d5-d98339b273f0.jpg)

Mine play store is also note working giving error 7 and my wifi is also not working I have a realtek 8822ce wifi adapter please help me sir

**Comment by Icey67** [comment] 2022-02-02 15:50
![image](https://user-images.githubusercontent.com/60461186/152188067-80a3064b-e6f2-45a6-8c51-10de6080d61b.png)
Everytime when i start ChromeOS, Android container errors keep appearing and will disappear by relogging but i'm sick of it,
Is there anyway i can permanently fix this?

**Comment by bybenjamin** [comment] 2023-05-31 14:40
Play Store and android won't open. Please can someone help me? @sebanc 
![Screenshot 2023-05-31 17 37 56](https://github.com/sebanc/brunch/assets/91468765/6644e96c-9cb6-4e37-bb2e-2150b95f322d)

**Comment by lfom** [comment] 2023-05-31 19:40
> Play Store and android won't open. Please can someone help me?

Have you tried using the newer kernel (6.1)? Same error? What is the output of the command below after a fresh boot?

    sudo dmesg | grep -i -e error -e fail

**Comment by bybenjamin** [comment] 2023-06-01 06:26
> > Play Store and android won't open. Please can someone help me?
> 
> Have you tried using the newer kernel (6.1)? Same error? What is the output of the command below after a fresh boot?
> 
> ```
> sudo dmesg | grep -i -e error -e fail
> ```

Yes still same.
![Screenshot 2023-06-01 09 24 25](https://github.com/sebanc/brunch/assets/91468765/900657df-4ff4-4950-b6f8-b3ce4634ec08)

**Comment by lfom** [comment] 2023-06-01 19:41
> Yes still same.

Last two lines are about arc errors, arc is the Android container/system. I can't really say what is going, but it may be related to a corrupted installation, you may want to try downloading and installing again, maybe an older version, and use the newer kernel if possible since it seems that your CPU is fairly new (2021). If nothing works, I'd suggest to gather all info and open a new issue.
