### ISSUE TITLE
A little help with broadcom wifi drivers

### ISSUE THREAD

**Issue by clandestinz** [sebanc/brunch#136] opened 2020-05-14 09:49 UTC
As the title says. I couldn't get the broadcom wifi drivers working. I don't see make installed. No dkms. Ideas?

**Comment by sebanc** [comment] 2020-05-14 10:13
Hi, the broadcom_wl dkms driver is already included but you have to add "options=broadcom_wl" to the kernel command line to activate it. (run "sudo edit-grub-config" and add "options=broadcom_wl" after cros_debug)

**Comment by clandestinz** [comment] 2020-05-14 10:30
im dumb i forgot about the options=

**Comment by RuhanN7** [comment] 2020-05-15 12:43
added the code and rebooted.. still wifi not working.

**Comment by sebanc** [comment] 2020-05-15 12:46
@RuhanN7 what's your laptop model ?

**Comment by RuhanN7** [comment] 2020-05-15 12:47
hp 15q-ds0004tu. There is no Linux Beta support too.

**Comment by sebanc** [comment] 2020-05-15 13:06
For wifi, could you attach a dmesg to this issue (run "dmesg > ~/Downloads\dmesg.txt" and attach the dmesg.txt file from your downloads folder). Also, could you post the output of "sudo lspci" ?

For linux beta, verify that you are using rammus recovery image and that virtualisation or vt-x is enabled in the bios.

**Comment by RuhanN7** [comment] 2020-05-15 13:40
Where to run this (dmesg > ~/Downloads\dmesg.txt) command? in Chrome browser terminal, it's not working.

Output of "sudo lspci"
chronos@localhost / $ sudo lspci
00:00.0 Host bridge: Intel Corporation Device 31f0 (rev 03)
00:00.1 Signal processing controller: Intel Corporation Device 318c (rev 03)
00:00.3 System peripheral: Intel Corporation Device 3190 (rev 03)
00:02.0 VGA compatible controller: Intel Corporation Device 3184 (rev 03)
00:0e.0 Audio device: Intel Corporation Device 3198 (rev 03)
00:0f.0 Communication controller: Intel Corporation Device 319a (rev 03)
00:12.0 SATA controller: Intel Corporation Device 31e3 (rev 03)
00:14.0 PCI bridge: Intel Corporation Device 31d6 (rev f3)
00:14.1 PCI bridge: Intel Corporation Device 31d7 (rev f3)
00:15.0 USB controller: Intel Corporation Device 31a8 (rev 03)
00:1f.0 ISA bridge: Intel Corporation Device 31e8 (rev 03)
00:1f.1 SMBus: Intel Corporation Device 31d4 (rev 03)
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device d723

**Comment by RuhanN7** [comment] 2020-05-15 13:51
I used rammus recovery in installation but Virtulisation was not enabled. I just enabled it and got Linux Beta option.. Thanks for that. Now Wifi and Bluetooth is the Problem.

**Comment by sebanc** [comment] 2020-05-15 13:57
Sorry the correct command is  "dmesg > ~/Downloads/dmesg.txt"

**Comment by RuhanN7** [comment] 2020-05-15 14:04
This the the dmesg code ouput
[dmesg.txt](https://github.com/sebanc/brunch/files/4634823/dmesg.txt)

**Comment by sebanc** [comment] 2020-05-15 14:31
@RuhanN7 your wifi module seems to be "rtl8188eus" which has no driver in the mainline linux kernel, I will try to include it and will update this issue when it is.

**Comment by RuhanN7** [comment] 2020-05-15 14:36
I will be greatful to you. If you solve the issue. I don't know the wifi module number. Probably you found it. 
Thank you in advance.

**Comment by RuhanN7** [comment] 2020-05-15 17:53
@sebanc can the "rtl8188eus" driver be installed through Terminal for now?

If possible, I got the Driver file.

Can you guide me by giving commands?

**Comment by sebanc** [comment] 2020-05-16 11:58
@RuhanN7 

Could you try the release in the "brunch-testing" repo (not this one) and boot with "options=rtl8188eu" added to the kernel command line ?

**Comment by RuhanN7** [comment] 2020-05-16 12:01
Didn't understand the brunch testing thing. But I can add the Line in Kernel Command and reboot. Can you elaborate?

**Comment by RuhanN7** [comment] 2020-05-16 12:03
@sebanc do I have install anything or just add the rtl command to kernel line and reboot?

**Comment by sebanc** [comment] 2020-05-16 12:14
Go back to my github account, instead of clicking on "brunch", look for "brunch-testing", download the release that is there and install it.
Before you boot the new release, add "options=rtl8188eu"

**Comment by RuhanN7** [comment] 2020-05-16 12:50
Did what you said. Wifi and Bluetooth still not working. Lost my Ethernet also.

**Comment by sebanc** [comment] 2020-05-16 13:08
Could you post a dmesg ? (run "dmesg > ~/Downloads/dmesg.txt" in crosh shell and attach dmesg.txt from your downloads folder to this issue)

**Comment by sebanc** [comment] 2020-05-16 13:14
Actually I forgot to include the firmware, could you download the below file:
https://github.com/lwfinger/rtl8188eu/raw/master/rtl8188eufw.bin

Then run "sudo cp ~/Downloads/rtl8188eufw.bin /lib/firmware/" and reboot.

If it still does not work, please attach the dmesg

**Comment by sebanc** [comment] 2020-05-16 13:20
Also, could you try booting with "options=rtl8188eu module_blacklist=r8188eu" added to the kernel command line ?

**Comment by clandestinz** [comment] 2020-05-16 13:21
love your support. keep it up

**Comment by RuhanN7** [comment] 2020-05-16 13:23
@sebanc should I reboot after installing firmware or should I enter the command after installing the firmware then reboot?

**Comment by sebanc** [comment] 2020-05-16 13:30
Enter the command before rebooting

**Comment by RuhanN7** [comment] 2020-05-16 13:32
@sebanc "sudo cp ~/Downloads/rtl8188eufw.bin /lib/firmware/rtlwifi/" this command didn't have any return. Is it meant to be that way?

It was like this..
chronos@localhost / $ sudo cp ~/Downloads/rtl8188eufw.bin /lib/firmware/rtlwifi/

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

chronos@localhost / $ sudo cp ~/Downloads/rtl8188eufw.bin /lib/firmware/rtlwifi/
chronos@localhost / $

**Comment by RuhanN7** [comment] 2020-05-16 13:38
@sebanc If you say it's ok. Then I will continue to add the command and reboot.

**Comment by sebanc** [comment] 2020-05-16 13:47
yes it is ok, you can reboot now

**Comment by RuhanN7** [comment] 2020-05-16 16:58
[dmesg.txt](https://github.com/sebanc/brunch/files/4638785/dmesg.txt)

Not working.. Ethernet too..

**Comment by sebanc** [comment] 2020-05-17 04:25
Sorry, just re-reading it and I think I mixed 2 different issues at some point, your wifi driver 
seems to be rtl8723de which I have also added at the same time, could you try to boot with "options=rtl8723de" ?

**Comment by RuhanN7** [comment] 2020-05-17 04:37
Should I delete last 2 commands?
Option enable and Blacklist?

**Comment by RuhanN7** [comment] 2020-05-17 04:39
> Also, could you try booting with "options=rtl8188eu module_blacklist=r8188eu" added to the kernel command line ?

Should I delete this two then reboot amd after that enter the new commands?

**Comment by sebanc** [comment] 2020-05-17 04:51
Yes please delete these 2

**Comment by RuhanN7** [comment] 2020-05-17 05:12
It worked. Wifi is online. Should I bother you with other issues? like Bluetooth?

**Comment by RuhanN7** [comment] 2020-05-17 05:13
Thanks a lot for the Wifi fix.

**Comment by sebanc** [comment] 2020-05-17 06:00
Could you send a new dmesg for bluetooth and explain the bootscreen and file transfer speed points ?

**Comment by RuhanN7** [comment] 2020-05-17 06:07
Earlier dmesg won't work?
Bluetooth not working at all.
Boot Screen shows enormous coding everytime I turn on the pc.
File transfer speed is too slow.

**Comment by sebanc** [comment] 2020-05-17 07:29
1) I need a new dmesg because the wifi driver was not loaded on previous one and wifi/bt are linked.
2) add "console=" to the kernel command line
3) File transfer speed only depends on the device you are using
4) add "options=enable_updates" to the kernel command line

**Comment by RuhanN7** [comment] 2020-05-17 07:34
added this "options=enable_updates" command after the rtl command to the kernel command line, it turned off wifi like before. Then I added "options=enable_updates" first then added "options=rtl8723de" . The wifi works now but not the update.

Wouldn't "console=" this command create the same problem that I just mentioned above?

**Comment by RuhanN7** [comment] 2020-05-17 07:41
[dmesg.txt](https://github.com/sebanc/brunch/files/4639834/dmesg.txt)
Here is the dmesg.

**Comment by sebanc** [comment] 2020-05-17 09:25
options have to be grouped together sperated by commas, in your case "options=rtl8723de,enable_updates". then you can a space and "console="

**Comment by sebanc** [comment] 2020-05-17 09:25
Sorry but I would need another dmesg taken after a fresh reboot

**Comment by RuhanN7** [comment] 2020-05-17 09:28
I will send you one. when it is done.

**Comment by RuhanN7** [comment] 2020-05-17 10:57
Updates and Boot Screen fixed. Thanks agiain.
[dmesg.txt](https://github.com/sebanc/brunch/files/4640093/dmesg.txt)
Dmesg for bluetooth.

**Comment by RuhanN7** [comment] 2020-05-18 13:16
This is the last major issue. Check if you can attend it please.

**Comment by sebanc** [comment] 2020-05-20 16:27
Could you try the release I have just uploaded in the "brunch-testing" repo (not this one) and attach another dmesg if bluetooth still does not work ?

**Comment by RuhanN7** [comment] 2020-05-20 16:37
Brunch r81 k4.19 testing 20200520
 This one?

**Comment by sebanc** [comment] 2020-05-20 16:45
Yes exactly

**Comment by RuhanN7** [comment] 2020-05-20 16:48
Internet is too slow because of Cyclone in my area. 
Will send the report to you , when it is done.

**Comment by RuhanN7** [comment] 2020-05-20 17:11
[dmesg.txt](https://github.com/sebanc/brunch/files/4658319/dmesg.txt)
Didn´t  Work.

**Comment by sebanc** [comment] 2020-05-20 17:19
Could you try to replace the content of /etc/init/rtl8723de.conf with:
```
start on stopped udev-trigger

script
	rmmod btrtl
	insmod /lib/modules/rtl8723de.ko
	modprobe btrtl
end script
```

And then reboot

**Comment by RuhanN7** [comment] 2020-05-20 17:34
Where to find the content and replace?

**Comment by sebanc** [comment] 2020-05-20 18:50
copy the text above
run "sudo nano /etc/init/rtl8723de.conf" in crosh shell
Delete the text in the file
Press CTRL+SHIFT+V to paste
then CTRL+X, "y" to save and enter

**Comment by RuhanN7** [comment] 2020-05-21 03:58
[dmesg.txt](https://github.com/sebanc/brunch/files/4660531/dmesg.txt)
Bluetooth still not working and The wifi stopped working after the command.

**Comment by RuhanN7** [comment] 2020-05-22 05:58
Can you give me the earlier script?

**Comment by sebanc** [comment] 2020-05-22 06:22
Here it is:
```
start on stopped udev-trigger

script
	insmod /lib/modules/rtl8723de.ko
end script
```

**Comment by sebanc** [comment] 2020-05-22 09:45
@RuhanN7 Could you try the new build there ?
https://github.com/sebanc/brunch-testing/releases

**Comment by RuhanN7** [comment] 2020-05-22 09:46
After installing the new build, Do I have edit any command?

**Comment by sebanc** [comment] 2020-05-22 09:48
No, no need to modify the script

**Comment by RuhanN7** [comment] 2020-05-22 11:28
[dmesg.txt](https://github.com/sebanc/brunch/files/4667751/dmesg.txt)
Didn´t work. Lost my Wifi again.

**Comment by RuhanN7** [comment] 2020-05-22 14:37
How to fix Wifi in this build?

**Comment by sebanc** [comment] 2020-05-22 14:49
Sorry but I made a change in the driver directly in this build which broke it, I hope you still have one of the previous build, else I will build another one tomorrow

**Comment by RuhanN7** [comment] 2020-05-22 14:50
How to downgrade to previous build?

**Comment by sebanc** [comment] 2020-05-22 15:21
The same way as to upgrade "sudo chromeos-update -f <path to the release archive>"

**Comment by RuhanN7** [comment] 2020-05-22 15:35
Okay. Thank You.

**Comment by sebanc** [comment] 2020-05-22 15:42
When you will have reinstalled the previous brunch version, could you try replacing /etc/init/rtl8723de.conf content with:
```
start on stopped udev-trigger

script
	insmod /lib/modules/rtl8723de.ko ant_sel=1 fwlps=0 swlps=0
end script
```

**Comment by RuhanN7** [comment] 2020-05-22 15:53
Ok. I will and let you know.

**Comment by RuhanN7** [comment] 2020-05-22 16:24
Changed the Script after installing. Bluetooth still not working.

**Comment by sebanc** [comment] 2020-05-23 12:58
I looked at the kernel module and there is no other obvious change to test, so I will just revert back to the working version in next release.

According to https://github.com/lwfinger/rtlwifi_new/issues/237, the issue you have is related to selecting the correct antenna by adding "ant_sel=X" (from 0 to 2) in the /etc/init/rtl8723de.conf script.

Here are other module parameters which might help:
ant_sel:Set to 1 or 2 to force antenna number (default 0) (int)
msi:Set to 1 to use MSI interrupts mode (default 0) (bool)
swenc:Set to 1 for software crypto (default 0) (bool)
ips:Set to 0 to not use link power save (default 1) (bool)
swlps:Set to 1 to use SW control power save (default 0) (bool)
fwlps:Set to 1 to use FW control power save (default 1) (bool)

**Comment by sebanc** [comment] 2020-05-23 12:59
Also, forgot to mention that some comment say that bluetooth is only working when wifi is disconnected and is very weak

**Comment by RuhanN7** [comment] 2020-05-23 13:46
So what are you suggesting me to do?
Guide the same. I will try that.

**Comment by sebanc** [comment] 2020-05-23 15:06
What I suggest is to adjust /etc/init/rtl8723de.conf with the options above by adding them after "insmod /lib/modules/rtl8723de.ko":
```
start on stopped udev-trigger

script
	insmod /lib/modules/rtl8723de.ko
end script
```

You can start by trying "ant_sel=0", then "ant_sel=1" if it does not work and eventually "ant_sel=2" to see if it changes something.

Then if nothing worked you can try the other options mentioned in my above post as well.

Also, just in case, you cannot pair your phone through the bluetooth menu in chromeos as there is a specific setup for phones. Try with a mouse, bluetooth headset / speakers or something like that.

**Comment by RuhanN7** [comment] 2020-05-23 16:37
Ok. I will try.

**Comment by RuhanN7** [comment] 2020-06-01 15:04
Just wanna let you know that I tried it all. Didn´t Work.

**Comment by sebanc** [comment] 2020-06-01 15:12
Do you know if bluetooth can work in a standard linux distro ?

**Comment by RuhanN7** [comment] 2020-06-01 15:17
I don't know. I never tried any linux distro.

**Comment by sebanc** [comment] 2020-06-01 15:29
I can add drivers as they are but I cannot rewrite them, especially when I don't have the corresponding hardware. If at some point you manage to get wifi and bluetooth working in a linux distro, tell me how you did and I can try to reproduce it but that's as far as I can go for now.

**Comment by sebanc** [comment] 2020-06-02 05:47
For now I will close it this issue, don't hesitate to re-open it or create another one if you have more info.

**Closed by sebanc** 2020-06-02 05:47 UTC

**Comment by RuhanN7** [comment] 2020-06-02 05:51
OK.

**Comment by sebanc** [comment] 2020-06-23 06:21
@RuhanN7 I tried to improve rtl8723de support in the new test build, you should not need to use "options=rtl8723de". Not sure about bluetooth though.

**Comment by weiliatrtp** [comment] 2020-12-30 03:56
> Hi, the broadcom_wl dkms driver is already included but you have to add "options=broadcom_wl" to the kernel command line to activate it. (run "sudo edit-grub-config" and add "options=broadcom_wl" after cros_debug)

this did work for my computer, thank you so much!

**Comment by gritikverma** [comment] 2024-09-08 19:25
Hi @sebanc  I am completely new here and have no idea how to put these commands and where to put m using brunch r107 and rammus v108 could you pls help me to fix my WiFi as well
